name: Create Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"

      - name: Zip python dependencies in Amazon Linux 2
        run: |
          python -m pip install --upgrade pip
          mkdir -p python
          uv export --no-hashes --format requirements-txt > requirements.txt
          
          docker run --rm -v $(pwd):/lambda_layer -w /lambda_layer \
            amazonlinux:2023 bash -c "\
              dnf install -y python3.11 python3.11-pip && \
              python3.11 -m pip install --upgrade pip && \
              python3.11 -m pip install -r requirements.txt -t python/ --only-binary=:all:"
          
          zip -r aws-lambda-python-dependencies-v0.0.${{ github.run_number }}.zip python/
          rm requirements.txt

      - name: Zip source codes
        run: |
          zip -r aws-lambda-source-codes-v0.0.${{ github.run_number }}.zip utils/ jobs/ calendars/ server/  
          ls -lh aws-lambda-source-codes-v0.0.${{ github.run_number }}.zip

      - name: Create GitHub Release (Source codes & Dependencies)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.${{ github.run_number }}
          name: "AWS Lambda Release v0.0.${{ github.run_number }}"
          body: "Release AWS Lambda source codes & dependencies v0.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            aws-lambda-source-codes-v0.0.${{ github.run_number }}.zip
            aws-lambda-python-dependencies-v0.0.${{ github.run_number }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

